
- name: Configuring Frontend
  hosts: frontend
  become: yes
  roles:
    - frontend

- name: Configuring Backend
  hosts: backend
  become: yes
  roles:
    - backend

- name: Configuring Mongo
  hosts: mongo
  become: yes
  roles:
    - mongo